// Pre-populated exercise library
// 50+ exercises with muscle groups, equipment, and default rest times

import type { Exercise, MuscleGroup, Equipment } from '../../types';

type ExerciseSeed = Omit<Exercise, 'id' | 'createdAt' | 'updatedAt'> & { tips?: string };

export const EXERCISE_LIBRARY: ExerciseSeed[] = [
  // ============ CHEST ============
  {
    name: 'Barbell Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Retract shoulder blades, arch back slightly, feet flat. Lower bar to mid-chest, press up and slightly back.',
  },
  {
    name: 'Incline Barbell Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Set bench to 30-45 degrees. Lower bar to upper chest. Keep elbows at 45-degree angle.',
  },
  {
    name: 'Dumbbell Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Greater range of motion than barbell. Keep dumbbells in line with mid-chest. Control the eccentric.',
  },
  {
    name: 'Incline Dumbbell Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Focus on upper chest stretch at bottom. Bring dumbbells together at top without clanking.',
  },
  {
    name: 'Dumbbell Flyes',
    muscleGroup: 'chest',
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Keep slight bend in elbows throughout. Feel the stretch, dont go too deep. Focus on the squeeze.',
  },
  {
    name: 'Cable Crossover',
    muscleGroup: 'chest',
    equipment: 'cable',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Lean slightly forward. Cross hands at bottom for full contraction. Control the negative.',
  },
  {
    name: 'Chest Dips',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Push-Ups',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Machine Chest Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Pec Deck Machine',
    muscleGroup: 'chest',
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
  },

  // ============ BACK ============
  {
    name: 'Barbell Deadlift',
    muscleGroup: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
  },
  {
    name: 'Conventional Deadlift',
    muscleGroup: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
  },
  {
    name: 'Barbell Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
  },
  {
    name: 'Pull-Ups',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Chin-Ups',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Lat Pulldown',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Seated Cable Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Dumbbell Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'T-Bar Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Face Pulls',
    muscleGroup: 'back',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ SHOULDERS ============
  {
    name: 'Overhead Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
  },
  {
    name: 'Seated Dumbbell Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Arnold Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Lateral Raises',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Front Raises',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Rear Delt Flyes',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Cable Lateral Raises',
    muscleGroup: 'shoulders',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Upright Rows',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },

  // ============ BICEPS ============
  {
    name: 'Barbell Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Dumbbell Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Hammer Curls',
    muscleGroup: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Preacher Curls',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Incline Dumbbell Curls',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Cable Curls',
    muscleGroup: 'biceps',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Concentration Curls',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ TRICEPS ============
  {
    name: 'Close Grip Bench Press',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Tricep Pushdown',
    muscleGroup: 'triceps',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Overhead Tricep Extension',
    muscleGroup: 'triceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Skull Crushers',
    muscleGroup: 'triceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Dips (Tricep Focus)',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Diamond Push-Ups',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ QUADRICEPS ============
  {
    name: 'Barbell Back Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Brace core, break at hips and knees together. Knees track over toes. Depth: hip crease below knee.',
  },
  {
    name: 'Front Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Keep elbows high, torso upright. More quad-dominant than back squat. Go only as deep as mobility allows.',
  },
  {
    name: 'Leg Press',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Dont lock out knees at top. Keep lower back pressed into pad. Foot placement changes emphasis.',
  },
  {
    name: 'Leg Extension',
    muscleGroup: 'quadriceps',
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Point toes up for more rectus femoris. Control the negative. Squeeze hard at the top.',
  },
  {
    name: 'Hack Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Keep back flat against pad. Lower foot placement = more quad. Higher = more glute.',
  },
  {
    name: 'Bulgarian Split Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Front foot far enough forward that knee stays over ankle. Lean torso slightly forward for more quad.',
  },
  {
    name: 'Walking Lunges',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Long steps for glutes, short steps for quads. Push through front heel. Keep torso upright.',
  },

  // ============ HAMSTRINGS ============
  {
    name: 'Romanian Deadlift',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
  },
  {
    name: 'Lying Leg Curl',
    muscleGroup: 'hamstrings',
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Seated Leg Curl',
    muscleGroup: 'hamstrings',
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Stiff-Leg Deadlift',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
  },
  {
    name: 'Good Mornings',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },

  // ============ GLUTES ============
  {
    name: 'Hip Thrust',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Glute Bridge',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Cable Kickbacks',
    muscleGroup: 'glutes',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Sumo Deadlift',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings', 'quadriceps', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
  },

  // ============ CALVES ============
  {
    name: 'Standing Calf Raises',
    muscleGroup: 'calves',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Seated Calf Raises',
    muscleGroup: 'calves',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Donkey Calf Raises',
    muscleGroup: 'calves',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ CORE ============
  {
    name: 'Plank',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Hanging Leg Raises',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Cable Crunches',
    muscleGroup: 'core',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Ab Wheel Rollout',
    muscleGroup: 'core',
    equipment: 'other',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Russian Twists',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Dead Bug',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ FOREARMS ============
  {
    name: 'Wrist Curls',
    muscleGroup: 'forearms',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Reverse Wrist Curls',
    muscleGroup: 'forearms',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Farmers Walk',
    muscleGroup: 'forearms',
    secondaryMuscles: ['core', 'shoulders'],
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
];

export default EXERCISE_LIBRARY;
