// Pre-populated exercise library
// 50+ exercises with muscle groups, equipment, and default rest times

import type { Exercise, MuscleGroup, Equipment } from '../../types';

type ExerciseSeed = Omit<Exercise, 'id' | 'createdAt' | 'updatedAt'> & { tips?: string };

export const EXERCISE_LIBRARY: ExerciseSeed[] = [
  // ============ CHEST ============
  {
    name: 'Barbell Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Retract shoulder blades, arch back slightly, feet flat. Lower bar to mid-chest, press up and slightly back.',
  },
  {
    name: 'Incline Barbell Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Set bench to 30-45 degrees. Lower bar to upper chest. Keep elbows at 45-degree angle.',
  },
  {
    name: 'Dumbbell Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Greater range of motion than barbell. Keep dumbbells in line with mid-chest. Control the eccentric.',
  },
  {
    name: 'Incline Dumbbell Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Focus on upper chest stretch at bottom. Bring dumbbells together at top without clanking.',
  },
  {
    name: 'Dumbbell Flyes',
    muscleGroup: 'chest',
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Keep slight bend in elbows throughout. Feel the stretch, dont go too deep. Focus on the squeeze.',
  },
  {
    name: 'Cable Crossover',
    muscleGroup: 'chest',
    equipment: 'cable',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Lean slightly forward. Cross hands at bottom for full contraction. Control the negative.',
  },
  {
    name: 'Chest Dips',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Push-Ups',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Machine Chest Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Pec Deck Machine',
    muscleGroup: 'chest',
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
  },

  // ============ BACK ============
  {
    name: 'Barbell Deadlift',
    muscleGroup: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
  },
  {
    name: 'Conventional Deadlift',
    muscleGroup: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
  },
  {
    name: 'Barbell Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
  },
  {
    name: 'Pull-Ups',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Chin-Ups',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Lat Pulldown',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Seated Cable Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Dumbbell Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'T-Bar Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Face Pulls',
    muscleGroup: 'back',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ SHOULDERS ============
  {
    name: 'Overhead Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
  },
  {
    name: 'Seated Dumbbell Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Arnold Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Lateral Raises',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Front Raises',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Rear Delt Flyes',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Cable Lateral Raises',
    muscleGroup: 'shoulders',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Upright Rows',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },

  // ============ BICEPS ============
  {
    name: 'Barbell Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Dumbbell Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Hammer Curls',
    muscleGroup: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Preacher Curls',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Incline Dumbbell Curls',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Cable Curls',
    muscleGroup: 'biceps',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Concentration Curls',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ TRICEPS ============
  {
    name: 'Close Grip Bench Press',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Tricep Pushdown',
    muscleGroup: 'triceps',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Overhead Tricep Extension',
    muscleGroup: 'triceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Skull Crushers',
    muscleGroup: 'triceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Dips (Tricep Focus)',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Diamond Push-Ups',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ QUADRICEPS ============
  {
    name: 'Barbell Back Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Brace core, break at hips and knees together. Knees track over toes. Depth: hip crease below knee.',
  },
  {
    name: 'Front Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Keep elbows high, torso upright. More quad-dominant than back squat. Go only as deep as mobility allows.',
  },
  {
    name: 'Leg Press',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Dont lock out knees at top. Keep lower back pressed into pad. Foot placement changes emphasis.',
  },
  {
    name: 'Leg Extension',
    muscleGroup: 'quadriceps',
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Point toes up for more rectus femoris. Control the negative. Squeeze hard at the top.',
  },
  {
    name: 'Hack Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Keep back flat against pad. Lower foot placement = more quad. Higher = more glute.',
  },
  {
    name: 'Bulgarian Split Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Front foot far enough forward that knee stays over ankle. Lean torso slightly forward for more quad.',
  },
  {
    name: 'Walking Lunges',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Long steps for glutes, short steps for quads. Push through front heel. Keep torso upright.',
  },

  // ============ HAMSTRINGS ============
  {
    name: 'Romanian Deadlift',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
  },
  {
    name: 'Lying Leg Curl',
    muscleGroup: 'hamstrings',
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Seated Leg Curl',
    muscleGroup: 'hamstrings',
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Stiff-Leg Deadlift',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
  },
  {
    name: 'Good Mornings',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },

  // ============ GLUTES ============
  {
    name: 'Hip Thrust',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Glute Bridge',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Cable Kickbacks',
    muscleGroup: 'glutes',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Sumo Deadlift',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings', 'quadriceps', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
  },

  // ============ CALVES ============
  {
    name: 'Standing Calf Raises',
    muscleGroup: 'calves',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Seated Calf Raises',
    muscleGroup: 'calves',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Donkey Calf Raises',
    muscleGroup: 'calves',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ CORE ============
  {
    name: 'Plank',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    trackingType: 'duration',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Hanging Leg Raises',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Cable Crunches',
    muscleGroup: 'core',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Ab Wheel Rollout',
    muscleGroup: 'core',
    equipment: 'other',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Russian Twists',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Dead Bug',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ FOREARMS ============
  {
    name: 'Wrist Curls',
    muscleGroup: 'forearms',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Reverse Wrist Curls',
    muscleGroup: 'forearms',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Farmers Walk',
    muscleGroup: 'forearms',
    secondaryMuscles: ['core', 'shoulders'],
    equipment: 'dumbbell',
    trackingType: 'weight_duration',
    defaultRestSeconds: 90,
    isCustom: false,
  },

  // ============ OLYMPIC LIFTS ============
  {
    name: 'Clean and Jerk',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'quadriceps', 'glutes', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Start with bar over mid-foot. Explosive hip extension, catch in front rack. Dip and drive overhead.',
  },
  {
    name: 'Snatch',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'back', 'quadriceps', 'glutes'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Wide grip. Explosive pull, receive bar overhead in deep squat. Keep bar close to body.',
  },
  {
    name: 'Power Clean',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'shoulders', 'quadriceps', 'glutes'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Pull from floor, catch in front rack without full squat. Focus on explosive hip extension.',
  },
  {
    name: 'Power Snatch',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'back', 'quadriceps'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Same as snatch but catch without deep squat. Great for developing power.',
  },
  {
    name: 'Hang Clean',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'shoulders', 'quadriceps'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Start from hang position above knees. Explosive hip drive, catch in front rack.',
  },
  {
    name: 'Hang Snatch',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'back', 'quadriceps'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Start from hang position. Wide grip, explosive pull to overhead catch.',
  },
  {
    name: 'Clean Pull',
    muscleGroup: 'back',
    secondaryMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Full clean pull without catch. Focus on triple extension at top.',
  },
  {
    name: 'Snatch Pull',
    muscleGroup: 'back',
    secondaryMuscles: ['quadriceps', 'glutes', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Wide grip pull without catch. Emphasize explosive hip extension.',
  },
  {
    name: 'Push Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps', 'quadriceps', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Dip with knees, drive up explosively through legs to press overhead.',
  },
  {
    name: 'Push Jerk',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps', 'quadriceps', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Dip and drive, drop under bar catching with arms locked. Stand up to complete.',
  },
  {
    name: 'Split Jerk',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps', 'quadriceps', 'glutes'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Dip and drive, split feet front/back while pressing overhead. Recover to standing.',
  },
  {
    name: 'Clean and Press',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'back', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Clean to front rack, then strict press overhead. Great strength builder.',
  },
  {
    name: 'Muscle Snatch',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['back', 'triceps'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Pull and press in one motion without dropping under. Good for technique work.',
  },
  {
    name: 'Overhead Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['shoulders', 'core', 'glutes'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Hold bar overhead with wide grip. Maintain stable overhead position throughout squat.',
  },
  {
    name: 'Snatch Grip Deadlift',
    muscleGroup: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'quadriceps'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Wide snatch grip. Great for building snatch pull strength and upper back.',
  },

  // ============ ADDITIONAL CHEST ============
  {
    name: 'Decline Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Set bench to 15-30 degree decline. Targets lower chest fibers.',
  },
  {
    name: 'Decline Dumbbell Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Incline Cable Flyes',
    muscleGroup: 'chest',
    equipment: 'cable',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Set cables low, fly up and together. Great upper chest isolation.',
  },
  {
    name: 'Svend Press',
    muscleGroup: 'chest',
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Squeeze plates together, press out and back. Constant tension on inner chest.',
  },
  {
    name: 'Diamond Push-Ups',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Wide Grip Push-Ups',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Landmine Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'One end of barbell in corner. Press up and away at angle.',
  },

  // ============ ADDITIONAL BACK ============
  {
    name: 'Pendlay Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Start each rep from floor. Explosive pull, controlled lower. Strict form.',
  },
  {
    name: 'Meadows Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Landmine setup, one arm row. Great for lat stretch and contraction.',
  },
  {
    name: 'Chest Supported Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Lie face down on incline bench. Removes lower back stress.',
  },
  {
    name: 'Kroc Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Heavy one-arm rows with slight body english. High reps, heavy weight.',
  },
  {
    name: 'Wide Grip Lat Pulldown',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Close Grip Lat Pulldown',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Straight Arm Pulldown',
    muscleGroup: 'back',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Keep arms straight throughout. Great lat isolation.',
  },
  {
    name: 'Rack Pulls',
    muscleGroup: 'back',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Deadlift from elevated pins. Focus on lockout strength.',
  },
  {
    name: 'Good Mornings',
    muscleGroup: 'back',
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Hinge at hips with bar on back. Keep slight knee bend.',
  },
  {
    name: 'Hyperextensions',
    muscleGroup: 'back',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Inverted Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Body horizontal under bar. Pull chest to bar.',
  },

  // ============ ADDITIONAL SHOULDERS ============
  {
    name: 'Seated Barbell Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
  },
  {
    name: 'Behind the Neck Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Only if you have good shoulder mobility. Lower behind head.',
  },
  {
    name: 'Z Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Seated on floor with legs extended. No back support or leg drive.',
  },
  {
    name: 'Viking Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Dumbbell Front Raise',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Cable Front Raise',
    muscleGroup: 'shoulders',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Lu Raises',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Front raise with thumbs up, continue overhead. Full shoulder ROM.',
  },
  {
    name: 'Cable Lateral Raise',
    muscleGroup: 'shoulders',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Machine Lateral Raise',
    muscleGroup: 'shoulders',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Rear Delt Flyes',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Bent over, fly dumbbells to sides. Target rear delts.',
  },
  {
    name: 'Reverse Pec Deck',
    muscleGroup: 'shoulders',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Cable Face Pull',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Pull to face, externally rotate at top. Great for shoulder health.',
  },
  {
    name: 'Bradford Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Alternate front and behind neck presses without lockout.',
  },

  // ============ ADDITIONAL LEGS ============
  {
    name: 'Pause Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Pause 2-3 seconds at bottom. Builds strength out of the hole.',
  },
  {
    name: 'Box Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Sit back to box, pause, explode up. Teaches proper hip mechanics.',
  },
  {
    name: 'Safety Bar Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'SSB shifts load forward. Easier on shoulders.',
  },
  {
    name: 'Zercher Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'core', 'biceps'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Hold bar in crook of elbows. Unique core and quad stimulus.',
  },
  {
    name: 'Anderson Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Start from pins at bottom. Builds concentric strength.',
  },
  {
    name: 'Sissy Squat',
    muscleGroup: 'quadriceps',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Lean back, knees forward. Intense quad isolation.',
  },
  {
    name: 'Pistol Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Sumo Deadlift',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Wide stance, toes out. More quad and hip dominant.',
  },
  {
    name: 'Deficit Deadlift',
    muscleGroup: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'quadriceps'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Stand on platform 1-4 inches. Increases ROM and leg drive.',
  },
  {
    name: 'Trap Bar Deadlift',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Neutral grip, stand inside bar. More upright torso.',
  },
  {
    name: 'Walking Lunges',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Reverse Lunges',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Step back instead of forward. Easier on knees.',
  },
  {
    name: 'Barbell Lunges',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Step Ups',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Hack Squat Machine',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Pendulum Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Belt Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'No spinal loading. Great for back-off sets or injuries.',
  },
  {
    name: 'Single Leg Press',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Single Leg Curl',
    muscleGroup: 'hamstrings',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Nordic Curl',
    muscleGroup: 'hamstrings',
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Kneel, lower body under control. Eccentric hamstring focus.',
  },
  {
    name: 'Glute Ham Raise',
    muscleGroup: 'hamstrings',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Hip Thrust',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Back on bench, drive hips up. Squeeze glutes at top.',
  },
  {
    name: 'Glute Bridge',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Cable Pull Through',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Frog Pumps',
    muscleGroup: 'glutes',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Feet together, knees out. High rep glute activation.',
  },
  {
    name: 'Donkey Calf Raise',
    muscleGroup: 'calves',
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Single Leg Calf Raise',
    muscleGroup: 'calves',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Tibialis Raise',
    muscleGroup: 'calves',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Toes up against wall, raise toes. Trains front of shin.',
  },

  // ============ ADDITIONAL ARMS ============
  {
    name: 'Barbell Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'EZ Bar Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Angled grip is easier on wrists.',
  },
  {
    name: 'Preacher Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Arm braced on pad. Isolates biceps, no cheating.',
  },
  {
    name: 'Spider Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Lie face down on incline. Arms hang straight down.',
  },
  {
    name: 'Concentration Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Elbow braced on thigh. Full isolation.',
  },
  {
    name: '21s',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: '7 bottom half, 7 top half, 7 full reps.',
  },
  {
    name: 'Drag Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Keep bar close to body, elbows back. Long head emphasis.',
  },
  {
    name: 'Bayesian Curl',
    muscleGroup: 'biceps',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Cable behind you. Great stretch position.',
  },
  {
    name: 'Close Grip Bench Press',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Hands shoulder width. Keep elbows tucked.',
  },
  {
    name: 'JM Press',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Hybrid of close grip bench and skull crusher.',
  },
  {
    name: 'Dips',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Stay upright to emphasize triceps.',
  },
  {
    name: 'Bench Dips',
    muscleGroup: 'triceps',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'French Press',
    muscleGroup: 'triceps',
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Standing or seated, lower behind head. Long head stretch.',
  },
  {
    name: 'Overhead Dumbbell Extension',
    muscleGroup: 'triceps',
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Cable Kickback',
    muscleGroup: 'triceps',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Reverse Grip Tricep Pushdown',
    muscleGroup: 'triceps',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ ADDITIONAL CORE ============
  {
    name: 'Pallof Press',
    muscleGroup: 'core',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Anti-rotation exercise. Press out and hold.',
  },
  {
    name: 'Woodchoppers',
    muscleGroup: 'core',
    equipment: 'cable',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'High to low or low to high. Rotational core.',
  },
  {
    name: 'Decline Sit-Ups',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'V-Ups',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Bicycle Crunches',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Mountain Climbers',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Bird Dog',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Hollow Body Hold',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    trackingType: 'duration',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'L-Sit',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    trackingType: 'duration',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Dragon Flag',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Advanced. Lower body under control, keep straight line.',
  },
  {
    name: 'Toes to Bar',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Weighted Plank',
    muscleGroup: 'core',
    equipment: 'other',
    trackingType: 'weight_duration',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Side Plank',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    trackingType: 'duration',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Suitcase Carry',
    muscleGroup: 'core',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    trackingType: 'weight_duration',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Single arm carry. Anti-lateral flexion.',
  },

  // ============ ADDITIONAL FOREARMS/GRIP ============
  {
    name: 'Dead Hang',
    muscleGroup: 'forearms',
    equipment: 'bodyweight',
    trackingType: 'duration',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Hang from bar as long as possible. Grip endurance.',
  },
  {
    name: 'Plate Pinch',
    muscleGroup: 'forearms',
    equipment: 'other',
    trackingType: 'weight_duration',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Pinch weight plates together. Thumb strength.',
  },
  {
    name: 'Gripper Crush',
    muscleGroup: 'forearms',
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Wrist Roller',
    muscleGroup: 'forearms',
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Roll weight up and down. Forearm burner.',
  },
  {
    name: 'Finger Curls',
    muscleGroup: 'forearms',
    equipment: 'barbell',
    defaultRestSeconds: 60,
    isCustom: false,
  },

  // ============ COMPOUND/FULL BODY ============
  {
    name: 'Thrusters',
    muscleGroup: 'full_body',
    secondaryMuscles: ['quadriceps', 'shoulders', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Front squat directly into push press. No pause at top.',
  },
  {
    name: 'Man Makers',
    muscleGroup: 'full_body',
    secondaryMuscles: ['chest', 'back', 'shoulders'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Push-up, row each arm, clean to thruster. Total body.',
  },
  {
    name: 'Turkish Get-Up',
    muscleGroup: 'full_body',
    secondaryMuscles: ['core', 'shoulders'],
    equipment: 'kettlebell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Stand up from floor holding weight overhead. Complex movement.',
  },
  {
    name: 'Kettlebell Swing',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings', 'core', 'shoulders'],
    equipment: 'kettlebell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Hinge at hips, snap forward. Dont squat the swing.',
  },
  {
    name: 'Goblet Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'kettlebell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Hold weight at chest. Great for learning squat pattern.',
  },
  {
    name: 'Kettlebell Clean',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'back'],
    equipment: 'kettlebell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Kettlebell Snatch',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'back', 'core'],
    equipment: 'kettlebell',
    defaultRestSeconds: 90,
    isCustom: false,
  },
  {
    name: 'Battle Ropes',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'core'],
    equipment: 'other',
    trackingType: 'duration',
    defaultRestSeconds: 60,
    isCustom: false,
  },
  {
    name: 'Sled Push',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'calves'],
    equipment: 'other',
    trackingType: 'weight_duration',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Sled Pull',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'hamstrings'],
    equipment: 'other',
    trackingType: 'weight_duration',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Tire Flips',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'quadriceps', 'shoulders'],
    equipment: 'other',
    defaultRestSeconds: 120,
    isCustom: false,
  },
  {
    name: 'Atlas Stones',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'biceps', 'core'],
    equipment: 'other',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Strongman lift. Load stone to platform.',
  },
  {
    name: 'Log Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'other',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Strongman pressing. Clean log to shoulders, press overhead.',
  },
  {
    name: 'Axle Deadlift',
    muscleGroup: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'forearms'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    isCustom: false,
    tips: 'Thick bar increases grip challenge.',
  },
  {
    name: 'Yoke Walk',
    muscleGroup: 'full_body',
    secondaryMuscles: ['core', 'quadriceps'],
    equipment: 'other',
    trackingType: 'weight_duration',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Carry heavy yoke on shoulders. Total body stability.',
  },

  // ============ CROSSFIT / FUNCTIONAL FITNESS ============
  {
    name: 'Wall Ball',
    muscleGroup: 'full_body',
    secondaryMuscles: ['quadriceps', 'shoulders', 'core'],
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Squat with medicine ball, throw to target on wall. Catch and repeat fluidly.',
  },
  {
    name: 'Box Jump',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'calves'],
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Explosive jump onto box. Step or jump down. Land softly.',
  },
  {
    name: 'Box Jump Over',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'calves'],
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Jump over box, landing on other side. For speed or lateral work.',
  },
  {
    name: 'Burpee',
    muscleGroup: 'full_body',
    secondaryMuscles: ['chest', 'core', 'shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Chest to floor, jump up with hands overhead. Keep moving.',
  },
  {
    name: 'Burpee Box Jump Over',
    muscleGroup: 'full_body',
    secondaryMuscles: ['quadriceps', 'chest'],
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Burpee facing box, jump over. Classic CrossFit combo.',
  },
  {
    name: 'Devil Press',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'back', 'core'],
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Burpee with dumbbells, swing to overhead in one motion.',
  },
  {
    name: 'Double Under',
    muscleGroup: 'calves',
    secondaryMuscles: ['shoulders', 'core'],
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Jump rope passes twice per jump. Wrist speed and timing.',
  },
  {
    name: 'Kipping Pull-Up',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Use hip drive to generate momentum. Efficient for high reps.',
  },
  {
    name: 'Butterfly Pull-Up',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Circular kipping motion. Fastest pull-up variation.',
  },
  {
    name: 'Chest to Bar Pull-Up',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Pull until chest touches bar. More ROM than chin over bar.',
  },
  {
    name: 'Bar Muscle-Up',
    muscleGroup: 'back',
    secondaryMuscles: ['triceps', 'core', 'shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Kipping or strict pull-up transitioning to dip above bar.',
  },
  {
    name: 'Ring Muscle-Up',
    muscleGroup: 'back',
    secondaryMuscles: ['triceps', 'core', 'shoulders'],
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Pull and transition to support on rings. False grip helps.',
  },
  {
    name: 'Ring Dip',
    muscleGroup: 'triceps',
    secondaryMuscles: ['chest', 'shoulders', 'core'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Dip on rings with control. Turn rings out at top.',
  },
  {
    name: 'Ring Row',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Body at angle, pull chest to rings. Scale by adjusting angle.',
  },
  {
    name: 'Strict Pull-Up',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'No kipping. Dead hang to chin over bar with control.',
  },
  {
    name: 'Strict Handstand Push-Up',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'bodyweight',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Against wall, lower head to floor, press up. No kipping.',
  },
  {
    name: 'Kipping Handstand Push-Up',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps', 'core', 'quadriceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Use hip/leg drive to assist pressing back up.',
  },
  {
    name: 'Wall Walk',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['core', 'chest'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Start in plank, walk feet up wall, hands toward wall, reverse.',
  },
  {
    name: 'Handstand Walk',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['core', 'triceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Walk on hands. Keep core tight, shift weight side to side.',
  },
  {
    name: 'Rope Climb',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'forearms', 'core'],
    equipment: 'other',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Use J-hook or S-wrap foot technique. Pull with arms, lock with feet.',
  },
  {
    name: 'Legless Rope Climb',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'forearms', 'core'],
    equipment: 'other',
    defaultRestSeconds: 150,
    isCustom: false,
    tips: 'Rope climb using arms only. Keep legs straight or in L-sit.',
  },
  {
    name: 'GHD Sit-Up',
    muscleGroup: 'core',
    secondaryMuscles: ['hip flexors'],
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Full ROM sit-up on GHD. Touch floor behind, sit up to parallel.',
  },
  {
    name: 'GHD Hip Extension',
    muscleGroup: 'glutes',
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Hips on pad, lower torso, squeeze glutes to rise.',
  },
  {
    name: 'Dumbbell Snatch',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'back', 'quadriceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Single arm snatch from floor to overhead. Alternate arms.',
  },
  {
    name: 'Dumbbell Clean',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'quadriceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Single or double dumbbell clean to shoulders.',
  },
  {
    name: 'Dumbbell Thruster',
    muscleGroup: 'full_body',
    secondaryMuscles: ['quadriceps', 'shoulders'],
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Front squat to push press with dumbbells.',
  },
  {
    name: 'Dumbbell Hang Clean',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'back'],
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Clean from hang position with dumbbells.',
  },
  {
    name: 'Sandbag Clean',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'biceps', 'core'],
    equipment: 'other',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Bear hug or lap clean sandbag to shoulders.',
  },
  {
    name: 'Sandbag Carry',
    muscleGroup: 'full_body',
    secondaryMuscles: ['core', 'back'],
    equipment: 'other',
    trackingType: 'weight_duration',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Bear hug carry. Awkward implement builds stability.',
  },
  {
    name: 'Sandbag Over Shoulder',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'shoulders', 'core'],
    equipment: 'other',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Clean and rotate bag over shoulder. Alternate sides.',
  },
  {
    name: 'D-Ball Clean',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'biceps'],
    equipment: 'other',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Clean deadball to shoulder. Similar to atlas stone.',
  },
  {
    name: 'D-Ball Over Shoulder',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'core'],
    equipment: 'other',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Lift deadball over shoulder. For time or reps.',
  },
  {
    name: 'Assault Bike',
    muscleGroup: 'full_body',
    secondaryMuscles: ['quadriceps', 'shoulders'],
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Fan bike with arm handles. For calories or distance.',
  },
  {
    name: 'Rowing (Erg)',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'quadriceps', 'core'],
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Drive with legs, lean back, pull to chest. Reverse sequence.',
  },
  {
    name: 'Ski Erg',
    muscleGroup: 'back',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Pull handles down like Nordic skiing. Hinge at hips.',
  },
  {
    name: 'Echo Bike',
    muscleGroup: 'full_body',
    secondaryMuscles: ['quadriceps', 'shoulders'],
    equipment: 'machine',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Similar to assault bike. Track calories or distance.',
  },
  {
    name: 'Sumo Deadlift High Pull',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'shoulders', 'quadriceps'],
    equipment: 'barbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Wide stance deadlift continuing to high pull. Elbows high.',
  },
  {
    name: 'Medicine Ball Clean',
    muscleGroup: 'full_body',
    secondaryMuscles: ['quadriceps', 'core'],
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Clean medicine ball from ground to front rack position.',
  },
  {
    name: 'Ball Slam',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'core', 'back'],
    equipment: 'other',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Lift slam ball overhead, throw to ground with force.',
  },
  {
    name: 'Wall Climb',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['chest', 'core'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'From ground, climb feet up wall to handstand, come back down.',
  },
  {
    name: 'Bear Crawl',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'core', 'quadriceps'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Hands and feet, knees low. Move forward or backward.',
  },
  {
    name: 'Shuttle Run',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['calves', 'hamstrings'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Sprint between lines, touch ground at each turn.',
  },
  {
    name: 'Pistol Squat (Alternating)',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Single leg squat, alternate legs each rep.',
  },
  {
    name: 'Air Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'bodyweight',
    defaultRestSeconds: 30,
    isCustom: false,
    tips: 'Bodyweight squat. Hip crease below knee. Stand fully.',
  },
  {
    name: 'Jumping Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'calves'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Squat down, explode up into jump. Land soft, repeat.',
  },
  {
    name: 'Jumping Lunge',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'calves'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Lunge position, jump and switch legs mid-air.',
  },
  {
    name: 'Knees to Elbows',
    muscleGroup: 'core',
    secondaryMuscles: ['hip flexors'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Hanging, bring knees to elbows. Kipping allowed.',
  },
  {
    name: 'Strict Toes to Bar',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Toes to bar with no kipping. Pure core strength.',
  },
  {
    name: 'Kipping Toes to Bar',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Use kip to swing toes up to bar. Efficient for high reps.',
  },
  {
    name: 'Sit-Up',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 30,
    isCustom: false,
    tips: 'Standard sit-up. Anchored or AbMat version.',
  },
  {
    name: 'V-Up',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Arms and legs lift together to form V shape.',
  },
  {
    name: 'Hollow Rock',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Hollow body position, rock forward and back.',
  },
  {
    name: 'Superman',
    muscleGroup: 'back',
    secondaryMuscles: ['glutes'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Lying face down, lift arms and legs off ground.',
  },
  {
    name: 'Single Unders',
    muscleGroup: 'calves',
    secondaryMuscles: ['shoulders'],
    equipment: 'other',
    defaultRestSeconds: 30,
    isCustom: false,
    tips: 'Standard jump rope. One pass per jump.',
  },
  {
    name: 'Overhead Walking Lunge',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['shoulders', 'core', 'glutes'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Hold weight overhead while lunging. Ultimate stability test.',
  },
  {
    name: 'Front Rack Lunge',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Bar in front rack position while lunging.',
  },
  {
    name: 'Cluster',
    muscleGroup: 'full_body',
    secondaryMuscles: ['quadriceps', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Squat clean directly into thruster. No pause.',
  },
  {
    name: 'Squat Clean',
    muscleGroup: 'full_body',
    secondaryMuscles: ['quadriceps', 'back', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Clean catching in full squat position. Stand to complete.',
  },
  {
    name: 'Squat Snatch',
    muscleGroup: 'full_body',
    secondaryMuscles: ['shoulders', 'quadriceps', 'back'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    isCustom: false,
    tips: 'Snatch catching in overhead squat. Stand to complete.',
  },
  {
    name: 'Unbroken',
    muscleGroup: 'full_body',
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Complete set without rest. Applies to any movement.',
  },
  {
    name: 'Touch and Go Deadlift',
    muscleGroup: 'back',
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    isCustom: false,
    tips: 'Deadlifts bouncing off floor. Maintain tension throughout.',
  },
  {
    name: 'Barbell Cycling',
    muscleGroup: 'full_body',
    secondaryMuscles: ['back', 'shoulders'],
    equipment: 'barbell',
    defaultRestSeconds: 60,
    isCustom: false,
    tips: 'Continuous barbell movements for speed. Efficiency key.',
  },
];

export default EXERCISE_LIBRARY;
